export interface SearchableCalculator {
  id: string;
  name: string;
  nameHi: string;
  slug: string;
  href: string;
  categoryId: string;
  categoryName: string;
  categoryNameHi: string;
  description: string;
  descriptionHi: string;
  icon: string;
  keywords: string[];
  popular?: boolean;
}

export const SEARCHABLE_CALCULATORS: SearchableCalculator[] = [
  // Loan Calculators
  {
    id: 'emi',
    name: 'EMI Calculator',
    nameHi: 'ईएमआई कैलकुलेटर',
    slug: 'emi',
    href: '/emi-calculator',
    categoryId: 'loan',
    categoryName: 'Loan Calculators',
    categoryNameHi: 'ऋण कैलकुलेटर',
    description: 'Calculate Equated Monthly Installment for any loan with amortization schedule',
    descriptionHi: 'किसी भी ऋण के लिए समान मासिक किश्त (EMI) और भुगतान अनुसूची की गणना करें',
    icon: '🏠',
    keywords: ['emi', 'loan', 'installment', 'interest', 'amortization', 'repayment', 'bank loan', 'monthly payment', 'किस्त', 'ईएमआई', 'कर्ज'],
    popular: true,
  },
  {
    id: 'home-loan',
    name: 'Home Loan EMI Calculator',
    nameHi: 'होम लोन ईएमआई कैलकुलेटर',
    slug: 'home-loan',
    href: '/home-loan-calculator',
    categoryId: 'loan',
    categoryName: 'Loan Calculators',
    categoryNameHi: 'ऋण कैलकुलेटर',
    description: 'Calculate home loan EMI with stamp duty, registration & tax benefits (80C & 24b)',
    descriptionHi: 'स्टाम्प शुल्क, पंजीकरण और कर छूट (80C और 24b) के साथ होम लोन ईएमआई निकालें',
    icon: '🏡',
    keywords: ['home loan', 'housing loan', 'property loan', 'mortgage', 'stamp duty', 'section 24b', '80c', 'घर का लोन', 'मकान लोन', 'गृह ऋण'],
    popular: true,
  },
  {
    id: 'personal-loan',
    name: 'Personal Loan EMI Calculator',
    nameHi: 'पर्सनल लोन ईएमआई',
    slug: 'personal-loan',
    href: '/personal-loan-calculator',
    categoryId: 'loan',
    categoryName: 'Loan Calculators',
    categoryNameHi: 'ऋण कैलकुलेटर',
    description: 'Calculate personal loan EMI, interest rate comparison & total payable amount',
    descriptionHi: 'पर्सनल लोन ईएमआई, ब्याज दर तुलना और कुल देय राशि की गणना करें',
    icon: '💳',
    keywords: ['personal loan', 'instant loan', 'salary loan', 'unsecured loan', 'पर्सनल लोन', 'व्यक्तिगत ऋण'],
  },
  {
    id: 'car-loan',
    name: 'Car Loan EMI Calculator',
    nameHi: 'कार लोन ईएमआई',
    slug: 'car-loan',
    href: '/car-loan-calculator',
    categoryId: 'loan',
    categoryName: 'Loan Calculators',
    categoryNameHi: 'ऋण कैलकुलेटर',
    description: 'Calculate monthly car loan EMI, on-road cost & down payment for new/used cars',
    descriptionHi: 'नई या पुरानी कार के लिए मासिक ईएमआई, ऑन-रोड कीमत और डाउन पेमेंट निकालें',
    icon: '🚗',
    keywords: ['car loan', 'auto loan', 'vehicle loan', 'bike loan', 'गाड़ी लोन', 'कार ऋण'],
  },
  {
    id: 'loan-prepayment',
    name: 'Loan Prepayment Calculator',
    nameHi: 'लोन प्रीपेमेंट कैलकुलेटर',
    slug: 'loan-prepayment',
    href: '/loan-prepayment-calculator',
    categoryId: 'loan',
    categoryName: 'Loan Calculators',
    categoryNameHi: 'ऋण कैलकुलेटर',
    description: 'Calculate interest savings & tenure reduction with part-payments and extra EMI',
    descriptionHi: 'अतिरिक्त किश्त या पार्ट पेमेंट करके ब्याज और समय की बचत की गणना करें',
    icon: '⚡',
    keywords: ['prepayment', 'part payment', 'foreclosure', 'loan tenure reduction', 'pre-close loan', 'लोन प्रीपेमेंट', 'ब्याज बचत'],
  },

  // Investment Calculators
  {
    id: 'sip',
    name: 'SIP Calculator',
    nameHi: 'सिप कैलकुलेटर (SIP)',
    slug: 'sip',
    href: '/sip-calculator',
    categoryId: 'investment',
    categoryName: 'Investment Calculators',
    categoryNameHi: 'निवेश कैलकुलेटर',
    description: 'Calculate wealth growth & compounding returns on mutual fund monthly SIP',
    descriptionHi: 'म्यूचुअल फंड मासिक एसआईपी पर मिलने वाले रिटर्न और वेल्थ ग्रोथ की गणना करें',
    icon: '📈',
    keywords: ['sip', 'mutual fund', 'systematic investment plan', 'equity', 'monthly investment', 'nav', 'सिप', 'म्यूचुअल फंड'],
    popular: true,
  },
  {
    id: 'lumpsum',
    name: 'Lumpsum Calculator',
    nameHi: 'एकमुश्त निवेश कैलकुलेटर',
    slug: 'lumpsum',
    href: '/lumpsum-calculator',
    categoryId: 'investment',
    categoryName: 'Investment Calculators',
    categoryNameHi: 'निवेश कैलकुलेटर',
    description: 'Calculate one-time mutual fund investment returns and compound growth over years',
    descriptionHi: 'एक बार में निवेश की गई एकमुश्त राशि पर मिलने वाले रिटर्न की गणना करें',
    icon: '💎',
    keywords: ['lumpsum', 'one time investment', 'mutual fund lumpsum', 'wealth gain', 'एकमुश्त', 'वन टाइम इन्वेस्टमेंट'],
  },
  {
    id: 'fd',
    name: 'FD Calculator',
    nameHi: 'एफडी कैलकुलेटर (Fixed Deposit)',
    slug: 'fd',
    href: '/fd-calculator',
    categoryId: 'investment',
    categoryName: 'Investment Calculators',
    categoryNameHi: 'निवेश कैलकुलेटर',
    description: 'Calculate Fixed Deposit maturity amount & interest with quarterly compounding',
    descriptionHi: 'फिक्स्ड डिपॉजिट (FD) की मैच्योरिटी राशि और तिमाही चक्रवृद्धि ब्याज निकालें',
    icon: '🏦',
    keywords: ['fd', 'fixed deposit', 'term deposit', 'bank fd', 'maturity interest', 'एफडी', 'फिक्स्ड डिपॉजिट'],
    popular: true,
  },
  {
    id: 'rd',
    name: 'RD Calculator',
    nameHi: 'आरडी कैलकुलेटर (Recurring Deposit)',
    slug: 'rd',
    href: '/rd-calculator',
    categoryId: 'investment',
    categoryName: 'Investment Calculators',
    categoryNameHi: 'निवेश कैलकुलेटर',
    description: 'Calculate Recurring Deposit maturity value and interest earned across tenures',
    descriptionHi: 'आवर्ती जमा (RD) की परिपक्वता राशि और ब्याज की सटीक गणना करें',
    icon: '📊',
    keywords: ['rd', 'recurring deposit', 'post office rd', 'monthly deposit', 'आरडी', 'आवर्ती जमा'],
  },
  {
    id: 'ppf',
    name: 'PPF Calculator',
    nameHi: 'पीपीएफ कैलकुलेटर (PPF)',
    slug: 'ppf',
    href: '/ppf-calculator',
    categoryId: 'investment',
    categoryName: 'Investment Calculators',
    categoryNameHi: 'निवेश कैलकुलेटर',
    description: 'Calculate Public Provident Fund 15-year maturity, 7.1% interest & 80C tax benefits',
    descriptionHi: 'पब्लिक प्रोविडेंट फंड (PPF) की 15-वर्षीय मैच्योरिटी राशि और 80C टैक्स छूट निकालें',
    icon: '🛡️',
    keywords: ['ppf', 'public provident fund', '80c tax saving', 'government scheme', 'eee status', 'पीपीएफ'],
    popular: true,
  },
  {
    id: 'epf',
    name: 'EPF Calculator',
    nameHi: 'ईपीएफ कैलकुलेटर (PF Balance)',
    slug: 'epf',
    href: '/epf-calculator',
    categoryId: 'investment',
    categoryName: 'Investment Calculators',
    categoryNameHi: 'निवेश कैलकुलेटर',
    description: 'Calculate Employee Provident Fund corpus, employer/employee share & 8.25% interest',
    descriptionHi: 'कर्मचारी भविष्य निधि (EPF) बैलेंस और 8.25% ब्याज दर के अनुसार फंड ग्रोथ निकालें',
    icon: '💼',
    keywords: ['epf', 'pf balance', 'provident fund', 'epfo', 'uan', 'retirement fund', 'पीएफ', 'ईपीएफ'],
  },
  {
    id: 'nps',
    name: 'NPS Calculator',
    nameHi: 'एनपीएस कैलकुलेटर (National Pension)',
    slug: 'nps',
    href: '/nps-calculator',
    categoryId: 'investment',
    categoryName: 'Investment Calculators',
    categoryNameHi: 'निवेश कैलकुलेटर',
    description: 'Calculate National Pension System corpus, lump-sum payout & monthly pension',
    descriptionHi: 'नेशनल पेंशन सिस्टम (NPS) से मिलने वाली कुल राशि और मासिक पेंशन निकालें',
    icon: '👴',
    keywords: ['nps', 'national pension system', 'pfrda', 'pension scheme', '80ccd', 'एनपीएस', 'पेंशन'],
  },
  {
    id: 'cagr',
    name: 'CAGR Calculator',
    nameHi: 'सीएजीआर कैलकुलेटर',
    slug: 'cagr',
    href: '/cagr-calculator',
    categoryId: 'investment',
    categoryName: 'Investment Calculators',
    categoryNameHi: 'निवेश कैलकुलेटर',
    description: 'Calculate Compound Annual Growth Rate and annualized returns on investments',
    descriptionHi: 'निवेश पर वार्षिक चक्रवृद्धि वृद्धि दर (CAGR) और रिटर्न की गणना करें',
    icon: '📉',
    keywords: ['cagr', 'compound annual growth rate', 'annual return', 'stock cagr', 'सीएजीआर'],
  },
  {
    id: 'compound-interest',
    name: 'Compound Interest Calculator',
    nameHi: 'चक्रवृद्धि ब्याज कैलकुलेटर',
    slug: 'compound-interest',
    href: '/compound-interest-calculator',
    categoryId: 'investment',
    categoryName: 'Investment Calculators',
    categoryNameHi: 'निवेश कैलकुलेटर',
    description: 'Calculate daily, monthly, quarterly & yearly compound interest with periodic additions',
    descriptionHi: 'दैनिक, मासिक, त्रैमासिक और वार्षिक चक्रवृद्धि ब्याज की त्वरित गणना करें',
    icon: '🔄',
    keywords: ['compound interest', 'ci', 'compounding', 'interest on interest', 'चक्रवृद्धि ब्याज'],
  },
  {
    id: 'simple-interest',
    name: 'Simple Interest Calculator',
    nameHi: 'साधारण ब्याज कैलकुलेटर',
    slug: 'simple-interest',
    href: '/simple-interest-calculator',
    categoryId: 'investment',
    categoryName: 'Investment Calculators',
    categoryNameHi: 'निवेश कैलकुलेटर',
    description: 'Calculate simple interest (P × R × T / 100) and total repayment amount',
    descriptionHi: 'मूलधन, दर और समय के आधार पर साधारण ब्याज (SI) की गणना करें',
    icon: '🪙',
    keywords: ['simple interest', 'si', 'p r t formula', 'interest rate', 'साधारण ब्याज'],
  },

  // Tax Calculators
  {
    id: 'income-tax',
    name: 'Income Tax Calculator FY 2025-26',
    nameHi: 'आयकर कैलकुलेटर (Income Tax)',
    slug: 'income-tax',
    href: '/income-tax-calculator',
    categoryId: 'tax',
    categoryName: 'Tax Calculators',
    categoryNameHi: 'कर कैलकुलेटर',
    description: 'Compare Old vs New Tax Regime with ₹75,000 standard deduction, 87A rebate & slabs',
    descriptionHi: 'पुराने और नए टैक्स रिजीम की तुलना करें और ₹75,000 स्टैंडर्ड डिडक्शन के साथ टैक्स निकालें',
    icon: '💸',
    keywords: ['income tax', 'tax calculator', 'old vs new regime', 'tax slabs', 'itr', '87a rebate', 'standard deduction', 'आयकर', 'टैक्स'],
    popular: true,
  },
  {
    id: 'gst',
    name: 'GST Calculator',
    nameHi: 'जीएसटी कैलकुलेटर (GST)',
    slug: 'gst',
    href: '/gst-calculator',
    categoryId: 'tax',
    categoryName: 'Tax Calculators',
    categoryNameHi: 'कर कैलकुलेटर',
    description: 'Add or remove GST with 3%, 5%, 12%, 18%, 28% slabs and CGST / SGST / IGST split',
    descriptionHi: 'जीएसटी जोड़ें या हटाएं (3%, 5%, 12%, 18%, 28%) और CGST, SGST, IGST अलग करें',
    icon: '🧾',
    keywords: ['gst', 'goods and services tax', 'cgst', 'sgst', 'igst', 'add gst', 'remove gst', 'reverse gst', 'जीएसटी'],
    popular: true,
  },
  {
    id: 'salary',
    name: 'Salary In-Hand Calculator',
    nameHi: 'इन-हैंड सैलरी कैलकुलेटर',
    slug: 'salary',
    href: '/salary-calculator',
    categoryId: 'tax',
    categoryName: 'Tax Calculators',
    categoryNameHi: 'कर कैलकुलेटर',
    description: 'Convert annual CTC to monthly in-hand take-home salary with PF, PT & tax deductions',
    descriptionHi: 'सालाना सीटीसी (CTC) से मासिक इन-हैंड (टेक होम) सैलरी और कटौतियों का हिसाब लगाएं',
    icon: '💵',
    keywords: ['salary', 'in hand salary', 'ctc to in hand', 'take home pay', 'payslip', 'basic pay', 'hra', 'सैलरी', 'वेतन'],
    popular: true,
  },
  {
    id: 'hra',
    name: 'HRA Exemption Calculator',
    nameHi: 'एचआरए छूट कैलकुलेटर (HRA)',
    slug: 'hra',
    href: '/hra-calculator',
    categoryId: 'tax',
    categoryName: 'Tax Calculators',
    categoryNameHi: 'कर कैलकुलेटर',
    description: 'Calculate House Rent Allowance tax exemption u/s 10(13A) for Metro (50%) & Non-Metro',
    descriptionHi: 'धारा 10(13A) के तहत मकान किराया भत्ता (HRA) कर छूट की गणना करें',
    icon: '🏢',
    keywords: ['hra', 'house rent allowance', 'rent exemption', 'section 10 13a', 'metro non metro rent', 'एचआरए'],
  },
  {
    id: 'gratuity',
    name: 'Gratuity Calculator',
    nameHi: 'ग्रेच्युटी कैलकुलेटर',
    slug: 'gratuity',
    href: '/gratuity-calculator',
    categoryId: 'tax',
    categoryName: 'Tax Calculators',
    categoryNameHi: 'कर कैलकुलेटर',
    description: 'Calculate gratuity payout under Payment of Gratuity Act with ₹20 Lakh tax exemption',
    descriptionHi: '5 वर्ष या अधिक की नौकरी के बाद मिलने वाली ग्रेच्युटी राशि और टैक्स छूट निकालें',
    icon: '🎁',
    keywords: ['gratuity', 'gratuity act 1972', 'retirement gratuity', 'service tenure', 'ग्रेच्युटी'],
  },

  // Retirement Calculators
  {
    id: 'retirement',
    name: 'Retirement Corpus Calculator',
    nameHi: 'सेवानिवृत्ति कोष कैलकुलेटर',
    slug: 'retirement',
    href: '/retirement-calculator',
    categoryId: 'retirement',
    categoryName: 'Retirement Calculators',
    categoryNameHi: 'सेवानिवृत्ति कैलकुलेटर',
    description: 'Estimate required retirement corpus factoring inflation, expenses & life expectancy',
    descriptionHi: 'महंगाई और भविष्य के खर्चों को जोड़कर रिटायरमेंट के लिए जरूरी फंड का अनुमान लगाएं',
    icon: '🌴',
    keywords: ['retirement', 'retirement planning', 'retirement corpus', 'pension goal', 'रिटायरमेंट'],
  },
  {
    id: 'inflation',
    name: 'Inflation Calculator',
    nameHi: 'मुद्रास्फीति (महंगाई) कैलकुलेटर',
    slug: 'inflation',
    href: '/inflation-calculator',
    categoryId: 'retirement',
    categoryName: 'Retirement Calculators',
    categoryNameHi: 'सेवानिवृत्ति कैलकुलेटर',
    description: 'Calculate future purchasing power loss & cost of living growth based on inflation rates',
    descriptionHi: 'महंगाई दर के आधार पर भविष्य में पैसों की घटी हुई कीमत और खर्चों का हिसाब लगाएं',
    icon: '📉',
    keywords: ['inflation', 'purchasing power', 'future cost', 'cpi', 'cost of living', 'महंगाई', 'मुद्रास्फीति'],
  },

  // Health Calculators
  {
    id: 'bmi',
    name: 'BMI Calculator',
    nameHi: 'बीएमआई कैलकुलेटर (Body Mass Index)',
    slug: 'bmi',
    href: '/bmi-calculator',
    categoryId: 'health',
    categoryName: 'Health Calculators',
    categoryNameHi: 'स्वास्थ्य कैलकुलेटर',
    description: 'Calculate Body Mass Index (BMI) and healthy weight range for adults & children',
    descriptionHi: 'अपनी ऊंचाई और वजन के आधार पर बॉडी मास इंडेक्स (BMI) और आदर्श वजन जानें',
    icon: '⚖️',
    keywords: ['bmi', 'body mass index', 'weight check', 'underweight', 'overweight', 'obesity', 'बीएमआई', 'वजन'],
    popular: true,
  },
  {
    id: 'bmr',
    name: 'BMR Calculator',
    nameHi: 'बीएमआर कैलकुलेटर (Basal Metabolic Rate)',
    slug: 'bmr',
    href: '/bmr-calculator',
    categoryId: 'health',
    categoryName: 'Health Calculators',
    categoryNameHi: 'स्वास्थ्य कैलकुलेटर',
    description: 'Calculate basal metabolic rate using Mifflin-St Jeor & Harris-Benedict formulas',
    descriptionHi: 'आराम की अवस्था में शरीर द्वारा जलाई जाने वाली न्यूनतम ऊर्जा (कैलोरी) निकालें',
    icon: '🔥',
    keywords: ['bmr', 'basal metabolic rate', 'resting calories', 'metabolism', 'बीएमआर'],
  },
  {
    id: 'calorie',
    name: 'Calorie & TDEE Calculator',
    nameHi: 'कैलोरी व टीडीईई कैलकुलेटर',
    slug: 'calorie',
    href: '/calorie-calculator',
    categoryId: 'health',
    categoryName: 'Health Calculators',
    categoryNameHi: 'स्वास्थ्य कैलकुलेटर',
    description: 'Calculate daily calorie needs (TDEE) and macro split for weight loss, maintenance or muscle gain',
    descriptionHi: 'वजन घटाने या बढ़ाने के लिए दैनिक कैलोरी और प्रोटीन/कार्ब्स की मात्रा निकालें',
    icon: '🥗',
    keywords: ['calorie', 'tdee', 'weight loss', 'diet plan', 'macros', 'protein', 'कैलोरी', 'डाइट'],
  },
  {
    id: 'body-fat',
    name: 'Body Fat Calculator',
    nameHi: 'बॉडी फैट कैलकुलेटर',
    slug: 'body-fat',
    href: '/body-fat-calculator',
    categoryId: 'health',
    categoryName: 'Health Calculators',
    categoryNameHi: 'स्वास्थ्य कैलकुलेटर',
    description: 'Calculate body fat percentage and lean mass using the US Navy tape measure method',
    descriptionHi: 'यूएस नेवी विधि द्वारा शरीर के फैट प्रतिशत और लीन बॉडी मास की गणना करें',
    icon: '📏',
    keywords: ['body fat', 'fat percentage', 'lean mass', 'navy method', 'बॉडी फैट'],
  },
  {
    id: 'pregnancy-due-date',
    name: 'Pregnancy Due Date Calculator',
    nameHi: 'गर्भावस्था की नियत तारीख कैलकुलेटर',
    slug: 'pregnancy-due-date',
    href: '/pregnancy-due-date-calculator',
    categoryId: 'health',
    categoryName: 'Health Calculators',
    categoryNameHi: 'स्वास्थ्य कैलकुलेटर',
    description: 'Calculate Estimated Due Date (EDD), trimesters and week-by-week pregnancy progress',
    descriptionHi: 'अंतिम माहवारी (LMP) या गर्भधारण तिथि से प्रसव की संभावित तारीख और सप्ताह जानें',
    icon: '🤰',
    keywords: ['pregnancy', 'due date', 'edd', 'delivery date', 'lmp', 'trimester', 'baby due date', 'प्रेगनेंसी', 'डिलीवरी तारीख'],
  },
  {
    id: 'edd',
    name: 'EDD Calculator & Tracker',
    nameHi: 'ईडीडी कैलकुलेटर व ट्रैकर',
    slug: 'edd-calculator',
    href: '/edd-calculator',
    categoryId: 'health',
    categoryName: 'Health Calculators',
    categoryNameHi: 'स्वास्थ्य कैलकुलेटर',
    description: 'Calculate Estimated Due Date (EDD) & track pregnancy week by week with scan schedule',
    descriptionHi: 'अपनी अनुमानित डिलीवरी तारीख (EDD) निकालें और सप्ताह-दर-सप्ताह प्रेग्नेंसी ट्रैक करें',
    icon: '👶',
    keywords: ['edd', 'edd tracker', 'calculate edd', 'edd calculator', 'estimated due date', 'edd by lmp', 'delivery date', 'pregnancy tracker', 'pregnancy week by week', 'due date', 'ईडीडी', 'डिलीवरी तारीख'],
    popular: true,
  },

  // Math & Exam Calculators
  {
    id: 'sarkari-exam-age',
    name: 'Sarkari Exam Age Calculator',
    nameHi: 'सरकारी परीक्षा आयु कैलकुलेटर',
    slug: 'sarkari-exam-age',
    href: '/sarkari-exam-age-calculator',
    categoryId: 'math',
    categoryName: 'Math & Utility Calculators',
    categoryNameHi: 'गणित व परीक्षा कैलकुलेटर',
    description: 'Check age eligibility & category relaxation (OBC/SC/ST/PwD) for UPSC, SSC, Banking, RRB & NDA',
    descriptionHi: 'UPSC, SSC, रेलवे, बैंक परीक्षाओं के लिए कटऑफ तारीख पर आयु पात्रता व आरक्षण छूट चेक करें',
    icon: '🎯',
    keywords: ['sarkari exam', 'sarkari result age', 'age limit', 'exam eligibility', 'upsc age limit', 'ssc cgl age', 'ibps age', 'rrb ntpc', 'nda age', 'age relaxation', 'cutoff date', 'सरकारी परीक्षा', 'उम्र पात्रता'],
    popular: true,
  },
  {
    id: 'age',
    name: 'Age Calculator',
    nameHi: 'आयु कैलकुलेटर (Age Calculator)',
    slug: 'age',
    href: '/age-calculator',
    categoryId: 'math',
    categoryName: 'Math Calculators',
    categoryNameHi: 'गणित कैलकुलेटर',
    description: 'Calculate exact chronological age in years, months, days, total hours & next birthday countdown',
    descriptionHi: 'जन्म तिथि से आज तक की सटीक उम्र साल, महीने, दिन, कुल घंटे और अगले जन्मदिन के दिन जानें',
    icon: '🎂',
    keywords: ['age', 'dob', 'date of birth', 'exact age', 'birthday countdown', 'how old am i', 'उम्र', 'आयु'],
    popular: true,
  },
  {
    id: 'date-difference',
    name: 'Date Difference Calculator',
    nameHi: 'तिथियों का अंतर कैलकुलेटर',
    slug: 'date-difference',
    href: '/date-difference-calculator',
    categoryId: 'math',
    categoryName: 'Math Calculators',
    categoryNameHi: 'गणित कैलकुलेटर',
    description: 'Calculate exact number of days, weeks, months & working days between two calendar dates',
    descriptionHi: 'दो तारीखों के बीच कुल दिन, सप्ताह, महीने और वर्किंग दिनों की गणना करें',
    icon: '📅',
    keywords: ['date difference', 'days between dates', 'working days', 'business days', 'तारीख का अंतर'],
  },
  {
    id: 'percentage',
    name: 'Percentage Calculator',
    nameHi: 'प्रतिशत कैलकुलेटर',
    slug: 'percentage',
    href: '/percentage-calculator',
    categoryId: 'math',
    categoryName: 'Math Calculators',
    categoryNameHi: 'गणित कैलकुलेटर',
    description: 'Calculate percentage of a number, percentage increase/decrease, marks & discounts',
    descriptionHi: 'किसी संख्या का प्रतिशत, प्रतिशत वृद्धि/कमी और छूट की तुरंत गणना करें',
    icon: '💯',
    keywords: ['percentage', 'percent', 'discount percentage', 'percent increase', 'marks percentage', 'प्रतिशत'],
  },
  {
    id: 'fraction',
    name: 'Fraction Calculator',
    nameHi: 'भिन्न कैलकुलेटर (Fraction)',
    slug: 'fraction',
    href: '/fraction-calculator',
    categoryId: 'math',
    categoryName: 'Math Calculators',
    categoryNameHi: 'गणित कैलकुलेटर',
    description: 'Add, subtract, multiply and divide fractions with step-by-step simplification working',
    descriptionHi: 'भिन्नों का जोड़, घटाव, गुणा, भाग और सरल रूप स्टेप-बाय-स्टेप निकालें',
    icon: '➗',
    keywords: ['fraction', 'simplify fractions', 'mixed numbers', 'improper fractions', 'भिन्न'],
  },
  {
    id: 'scientific',
    name: 'Scientific Calculator Online',
    nameHi: 'वैज्ञानिक कैलकुलेटर',
    slug: 'scientific',
    href: '/scientific-calculator',
    categoryId: 'math',
    categoryName: 'Math Calculators',
    categoryNameHi: 'गणित कैलकुलेटर',
    description: 'Full scientific calculator with trigonometry, logarithms, powers, roots, factorial & history',
    descriptionHi: 'त्रिकोणमिति, लॉग, घात, वर्गमूल और इतिहास सुविधा वाला ऑनलाइन वैज्ञानिक कैलकुलेटर',
    icon: '🧮',
    keywords: ['scientific calculator', 'trigonometry', 'sin cos tan', 'log', 'square root', 'वैज्ञानिक कैलकुलेटर'],
  },

  // Regional Land & Utility
  {
    id: 'land-unit-converter',
    name: 'State-Wise Land Unit Converter',
    nameHi: 'राज्यवार भूमि माप कनवर्टर (Bigha to Sq Ft)',
    slug: 'land-unit-converter',
    href: '/land-unit-converter',
    categoryId: 'utility',
    categoryName: 'Utility Calculators',
    categoryNameHi: 'उपयोगिता कैलकुलेटर',
    description: 'Convert Bigha, Katha, Dhur, Biswa, Guntha, Kanal to Sq Ft & Acre across UP, Bihar, Punjab, etc.',
    descriptionHi: 'यूपी, बिहार, पंजाब, महाराष्ट्र आदि राज्यों के लिए बीघा, कट्ठा, धूर, बिस्वा, गुंठा को वर्ग फीट में बदलें',
    icon: '🌾',
    keywords: ['land converter', 'bigha', 'katha', 'dhur', 'biswa', 'guntha', 'kanal', 'marla', 'acre', 'hectare', 'decimal', 'dismil', 'zamin map', 'jamin napna', 'sq ft', 'बीघा', 'कट्ठा', 'जमीन माप'],
    popular: true,
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter (All Units)',
    nameHi: 'यूनिट कनवर्टर',
    slug: 'unit-converter',
    href: '/unit-converter',
    categoryId: 'utility',
    categoryName: 'Utility Calculators',
    categoryNameHi: 'उपयोगिता कैलकुलेटर',
    description: 'Convert length, weight, area, volume, temperature & speed with Indian & metric units',
    descriptionHi: 'लंबाई, वजन, क्षेत्रफल, आयतन, तापमान और गति की इकाइयों को आपस में बदलें',
    icon: '📐',
    keywords: ['unit converter', 'length converter', 'weight converter', 'area conversion', 'tola to gram', 'इकाई परिवर्तक'],
  },
  {
    id: 'gpa',
    name: 'GPA & CGPA to Percentage Calculator',
    nameHi: 'जीपीए / सीजीपीए से प्रतिशत कैलकुलेटर',
    slug: 'gpa',
    href: '/gpa-calculator',
    categoryId: 'utility',
    categoryName: 'Utility Calculators',
    categoryNameHi: 'उपयोगिता कैलकुलेटर',
    description: 'Convert 10-point Indian CGPA/SGPA to percentage using standard 9.5 multiplier & 4.0 scale',
    descriptionHi: '10-पॉइंट सीजीपीए या एसजीपीए को 9.5 फॉर्मूले से प्रतिशत और 4.0 GPA में बदलें',
    icon: '🎓',
    keywords: ['cgpa to percentage', 'gpa calculator', 'sgpa', 'marks to percentage', 'cbse cgpa', 'aktu vtu cgpa', 'सीजीपीए'],
  },
  {
    id: 'tip',
    name: 'Tip & Bill Split Calculator',
    nameHi: 'टिप व बिल स्प्लिट कैलकुलेटर',
    slug: 'tip',
    href: '/tip-calculator',
    categoryId: 'utility',
    categoryName: 'Utility Calculators',
    categoryNameHi: 'उपयोगिता कैलकुलेटर',
    description: 'Split restaurant food bills evenly among friends, calculate tips & review Indian service charges',
    descriptionHi: 'दोस्तों में रेस्टोरेंट बिल बराबर बांटें और सर्विस चार्ज व टिप का हिसाब लगाएं',
    icon: '🍽️',
    keywords: ['tip calculator', 'bill split', 'restaurant bill', 'service charge india', 'बिल स्प्लिट'],
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter (Live Forex & Dollar Rate)',
    nameHi: 'लाइव करेंसी कनवर्टर (डॉलर रेट)',
    slug: 'currency-converter',
    href: '/currency-converter',
    categoryId: 'utility',
    categoryName: 'Utility Calculators',
    categoryNameHi: 'उपयोगिता कैलकुलेटर',
    description: 'Live forex converter: dollar rate today, USD to INR, AED to INR, Euro to Rs & Pound to Rupee',
    descriptionHi: 'लाइव मुद्रा विनिमय: आज का डॉलर रेट (USD to INR), दिरहम (AED to INR), यूरो व पाउंड भाव',
    icon: '💱',
    keywords: [
      'dollar rate',
      'xe currency converter',
      'aed to inr',
      'today dollar rate',
      'usd rate',
      'dollar to rupee',
      'todays dollar rate',
      'british pound to inr',
      'us dollar to rupees',
      'euro to rs',
      'euro in indian rupees',
      'pound to indian rupees',
      'pound sterling to inr',
      'usd dollar rate',
      'australian dollar in indian rupees',
      'aed in rupees',
      'aed to rs',
      'dirham in indian rupees',
      'dolar to inr',
      'us dollar in indian rupees',
      'currency converter',
      'usd to indian rupees',
      'usd in inr',
      'forex rates',
      'exchange rate',
      'डॉलर रेट',
      'रुपया कनवर्टर',
      'दिरहम रेट'
    ],
    popular: true,
  },
];

export function searchCalculators(query: string, language: 'en' | 'hi' = 'en'): SearchableCalculator[] {
  if (!query || !query.trim()) return [];

  const raw = query.toLowerCase().trim();
  const tokens = raw.split(/\s+/).filter(Boolean);

  const scored = SEARCHABLE_CALCULATORS.map(calc => {
    let score = 0;
    const nameStr = (language === 'hi' ? `${calc.nameHi} ${calc.name}` : `${calc.name} ${calc.nameHi}`).toLowerCase();
    const catStr = (language === 'hi' ? `${calc.categoryNameHi} ${calc.categoryName}` : `${calc.categoryName} ${calc.categoryNameHi}`).toLowerCase();
    const descStr = (language === 'hi' ? calc.descriptionHi : calc.description).toLowerCase();
    const keywordsStr = calc.keywords.join(' ').toLowerCase();

    // Exact name match
    if (nameStr === raw) score += 100;
    else if (nameStr.startsWith(raw)) score += 60;
    else if (nameStr.includes(raw)) score += 40;

    // Tokens match
    tokens.forEach(tok => {
      if (nameStr.includes(tok)) score += 25;
      if (keywordsStr.includes(tok)) score += 20;
      if (catStr.includes(tok)) score += 10;
      if (descStr.includes(tok)) score += 5;
    });

    if (calc.popular) score += 2;

    return { calc, score };
  });

  return scored
    .filter(item => item.score > 0)
    .sort((a, b) => b.score - a.score)
    .map(item => item.calc);
}

export const POPULAR_SEARCH_KEYWORDS = [
  { label: 'Dollar Rate (USD to INR)', labelHi: 'डॉलर रेट (रुपया)', href: '/currency-converter' },
  { label: 'Home Loan EMI', labelHi: 'होम लोन ईएमआई', href: '/home-loan-calculator' },
  { label: 'SIP Calculator', labelHi: 'सिप कैलकुलेटर', href: '/sip-calculator' },
  { label: 'Income Tax FY 25-26', labelHi: 'आयकर कैलकुलेटर', href: '/income-tax-calculator' },
  { label: 'Sarkari Exam Age', labelHi: 'सरकारी परीक्षा आयु', href: '/sarkari-exam-age-calculator' },
  { label: 'Land Unit (Bigha/Sq Ft)', labelHi: 'भूमि माप (बीघा)', href: '/land-unit-converter' },
  { label: 'GST Calculator', labelHi: 'जीएसटी', href: '/gst-calculator' },
  { label: 'Salary In-Hand', labelHi: 'टेक-होम सैलरी', href: '/salary-calculator' },
  { label: 'EDD Tracker (Due Date)', labelHi: 'ईडीडी ट्रैकर', href: '/edd-calculator' },
  { label: 'BMI Calculator', labelHi: 'बीएमआई', href: '/bmi-calculator' },
];
